### ISSUE TITLE
Cracked Purpur Blocks do not mine faster when using a pickaxe

### ISSUE THREAD

**Issue by lambsie11** [FrozenBlock/TrailierTales#10]
**Description of the Bug Encountered**
Cracked Purpur Blocks do not have the 'mineable/pickaxe' tag applied to them, despite it seeming logical that they should, based off the fact vanilla Purpur Blocks have it.

**Steps To Reproduce**
1. Place/Find a Cracked Purpur Block
2. Try to mine it in survival mode with a pickaxe
3. Realise it's as slow to mine when mining it with your fists

**Expected Behavior**
It should mine faster when using a pickaxe.

**Comment by AViewFromTheTop** [comment]
Thank you!
Will be fixed in 1.1.
