### ISSUE TITLE
Polished Calcite Wall not appearing in stonecutter recipes

### ISSUE THREAD

**Issue by atLancelot** [FrozenBlock/TrailierTales#11]
Hello! I stumbled across an inconsistency in the calcite block family. When using a stonecutter, it seems the recipe for the polished wall does not appear, however is still able to be crafted in a crafting table. This happens whether you use polished calcite or regular calcite in the bench. Regular calcite walls, and polished calcite stairs work, so it might be something that was missed? I am using version 1.0.5 for fabric 1.21.1.

**Screenshots**
![image_2024-11-24_132915598](https://github.com/user-attachments/assets/f622b3e9-e2b8-459f-b240-2f21b1379e21)

**Additional context**
No additional notes, just wanted to say I've been loving this mod! Excellent work! :D

**Comment by AViewFromTheTop** [comment]
Thanks for reporting this! After the 1.21.4 port is done, I’ll get on this.
Also, what exactly do you like about the mod? We haven’t gotten too much feedback at this point, so any is appreciated.

**Comment by atLancelot** [comment]
I have been on the look out for mods that expand on archeology. Between that, the new building blocks, and other new mechanics, this mod rejuvenated my excitement for exploration. The additions this introduces is well implemented, and seamlessly blends into the base game. I haven't had the chance to explore _all_ of the new content, but from what I have played around with, I have been having a ton of fun!

**Comment by AViewFromTheTop** [comment]
> I have been on the look out for mods that expand on archeology. Between that, the new building blocks, and other new mechanics, this mod rejuvenated my excitement for exploration. The additions this introduces is well implemented, and seamlessly blends into the base game. I haven't had the chance to explore _all_ of the new content, but from what I have played around with, I have been having a ton of fun!

I really appreciate it!
